name: Java CI

on: [push]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (compile only)
        run: mvn clean compile

      - name: Run Tests
        run: mvn test

      - name: Package Application
        run: mvn package
